name: Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Логін в GitHub Container Registry
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    # Запуск kaniko для побудови і пушу образу
    - name: Build and push Docker image with Kaniko
      run: |
        mkdir -p /tmp/kaniko/.docker
        echo "{\"auths\":{\"ghcr.io\":{\"username\":\"${{ github.actor }}\",\"password\":\"${{ secrets.CR_PAT }}\"}}}" > /tmp/kaniko/.docker/config.json

        docker run --rm \
          -v "$(pwd)":/workspace \
          -v /tmp/kaniko/.docker:/kaniko/.docker \
          gcr.io/kaniko-project/executor:debug \
          --skip-tls-verify \
          --context /workspace \
          --dockerfile /workspace/Dockerfile \
          --destination ghcr.io/rossertylave/test:main \
          --cache=true \
          --cache-repo ghcr.io/rossertylave/test
