name: Build & Push Docker image with Kaniko on Commit

on:
  push:  # триггер на кожен коміт у будь-яку гілку
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/kaniko-project/executor:debug
      options: --entrypoint=""
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure Docker authentication
        run: |
          mkdir -p /kaniko/.docker
          echo "{\"auths\":{\"ghcr.io\":{\"username\":\"${{ secrets.GHCR_USERNAME }}\",\"password\":\"${{ secrets.GHCR_TOKEN }}\"}}}" > /kaniko/.docker/config.json

      - name: Build and push image with Kaniko
        run: |
          /kaniko/executor \
            --skip-tls-verify \
            --cache=true \
            --cache-repo ghcr.io/${{ github.repository }} \
            --context $GITHUB_WORKSPACE \
            --dockerfile $GITHUB_WORKSPACE/Dockerfile \
            --destination ghcr.io/${{ github.repository }}:${{ github.ref_name }}

