name: Build & Push Docker image with Kaniko

on:
  push:
    branches:
      - '**'  # усі гілки

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker auth config for GHCR
        run: |
          mkdir -p /tmp/kaniko/.docker
          echo "{\"auths\":{\"ghcr.io\":{\"username\":\"${{ secrets.GHCR_USERNAME }}\",\"password\":\"${{ secrets.GHCR_TOKEN }}\"}}}" > /tmp/kaniko/.docker/config.json

      - name: Run Kaniko to build and push
        run: |
          docker run --rm \
            -v "$(pwd)":/workspace \
            -v /tmp/kaniko/.docker:/kaniko/.docker \
            gcr.io/kaniko-project/executor:debug \
            --skip-tls-verify \
            --context /workspace \
            --dockerfile /workspace/Dockerfile \
            --destination ghcr.io/${{ github.repository }}:${{ github.ref_name }} \
            --cache=true \
            --cache-repo ghcr.io/${{ github.repository }}
